create table PRIVATE_COACH (
    COACH_ID int not null,
    CUSTOMER_ID int not null,
    COURSE_NAME VARCHAR(100),
    COURSE_DATE VARCHAR(100),
    UNIQUE (CUSTOMER_ID),
    FOREIGN KEY (COACH_ID) REFERENCES EMPLOYEE(USER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);