create table CUSTOMER_SELECT_COURSE (
    CUSTOMER_ID int not null,
    COURSE_ID int not null,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);