insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('Tom', '5f4dcc3b5aa765d61d8327deb882cf99','tom@abc.com', 16);
insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('Jerry', '5f4dcc3b5aa765d61d8327deb882cf99','jerry@abc.com', 17);
insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('Red', '5f4dcc3b5aa765d61d8327deb882cf99','red@abc.com', 18);
insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('Marry', '5f4dcc3b5aa765d61d8327deb882cf99','marry@abc.com', 19);
insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('James', '5f4dcc3b5aa765d61d8327deb882cf99','james@abc.com', 20);
insert into USER ( NAME, PASSWORD, EMAIL, AGE) values ('Emma', '5f4dcc3b5aa765d61d8327deb882cf99','emma@abc.com', 21);

insert into EMPLOYEE (USER_ID, JOB ) values (1,'HR');
insert into EMPLOYEE (USER_ID, JOB ) values (2,'OPs');
insert into EMPLOYEE (USER_ID, JOB ) values (3,'COACH');
insert into EMPLOYEE (USER_ID, JOB ) values (4,'COACH');
insert into EMPLOYEE (USER_ID, JOB ) values (5,'COACH');
insert into EMPLOYEE (USER_ID, JOB ) values (6,'COACH');

insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusOne','CusOne@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusTwo','CusTwo@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusThree','CusThree@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusFour','CusFour@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusFive','CusFive@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusSix','CusSix@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusSeven','CusSeven@bbd.com',19);
insert into CUSTOMER (NAME, EMAIL, AGE) values ('CusEight','CusEight@bbd.com',19);

insert into COURSE (COACH_ID, COURSE_NAME) values (3,'Java');
insert into COURSE (COACH_ID, COURSE_NAME) values (3,'Haskell');
insert into COURSE (COACH_ID, COURSE_NAME) values (4,'C++');
insert into COURSE (COACH_ID, COURSE_NAME) values (5,'Rust');
insert into COURSE (COACH_ID, COURSE_NAME) values (6,'Swift');
insert into COURSE (COACH_ID, COURSE_NAME) values (6,'Objective-C');

insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-01');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-02');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-03');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-04');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-05');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-06');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (1,'2015-07-07');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (2,'2015-07-01');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (2,'2015-07-03');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (2,'2015-07-05');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (2,'2015-07-07');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (2,'2015-07-09');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (3,'2015-07-02');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (3,'2015-07-04');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (3,'2015-07-06');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (3,'2015-07-08');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (3,'2015-07-10');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-02');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-03');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-04');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-05');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-06');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (4,'2015-07-07');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-01');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-02');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-03');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-04');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-05');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-06');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (5,'2015-07-06');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (6,'2015-07-10');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (6,'2015-07-11');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (6,'2015-07-12');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (6,'2015-07-13');
insert into COURSE_DATE (COURSE_ID, COURSE_DATE) values (6,'2015-07-14');

insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (3,1);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (3,2);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (4,3);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (4,4);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (6,5);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (5,6);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (5,7);
insert into PRIVATE_COACH (COACH_ID, CUSTOMER_ID) values (6,8);

insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (1,3);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (1,4);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (1,5);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (2,5);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (3,4);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (4,3);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (5,2);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (6,1);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (7,2);
insert into CUSTOMER_SELECT_COURSE (CUSTOMER_ID, COURSE_ID) values (8,5);
